export const SCAMS_SUCCESSFULLY_REGISTERED = 'SCAMS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_SCAMS_FAILED = 'REGISTERING_SCAMS_FAILED';


export const REGISTERED_SCAMS_FETCHED_SUCCESSFULLY = 'REGISTERED_SCAMS_FETCHED_SUCCESSFULLY';
export const REGISTERED_SCAMS_EMPTY_RESULTS = 'REGISTERED_SCAMS_EMPTY_RESULTS';
export const ERROR_FETCHING_SCAMS = 'ERROR_FETCHING_SCAMS';



