export const COUNTY_SUCCESSFULLY_REGISTERED = 'COUNTY_SUCCESSFULLY_REGISTERED';
export const REGISTERING_COUNTY_FAILED = 'REGISTERING_COUNTY_FAILED';


export const REGISTERED_COUNTY_FETCHED_SUCCESSFULLY = 'REGISTERED_COUNTY_FETCHED_SUCCESSFULLY';
export const REGISTERED_COUNTY_EMPTY_RESULTS = 'REGISTERED_COUNTY_EMPTY_RESULTS';
export const ERROR_FETCHING_COUNTY = 'ERROR_FETCHING_COUNTY';



