export const PREVENTIONS_SUCCESSFULLY_REGISTERED = 'PREVENTIONS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_PREVENTIONS_FAILED = 'REGISTERING_PREVENTIONS_FAILED';


export const REGISTERED_PREVENTIONS_FETCHED_SUCCESSFULLY = 'REGISTERED_PREVENTIONS_FETCHED_SUCCESSFULLY';
export const REGISTERED_PREVENTIONS_EMPTY_RESULTS = 'REGISTERED_PREVENTIONS_EMPTY_RESULTS';
export const ERROR_FETCHING_PREVENTIONS = 'ERROR_FETCHING_PREVENTIONS';



