export const TREATMENT_SUCCESSFULLY_REGISTERED = 'TREATMENT_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TREATMENT_FAILED = 'REGISTERING_TREATMENT_FAILED';


export const REGISTERED_TREATMENT_FETCHED_SUCCESSFULLY = 'REGISTERED_TREATMENT_FETCHED_SUCCESSFULLY';
export const REGISTERED_TREATMENT_EMPTY_RESULTS = 'REGISTERED_TREATMENT_EMPTY_RESULTS';
export const ERROR_FETCHING_TREATMENT = 'ERROR_FETCHING_TREATMENT';



