export const MYTHSDESCRIPTION_SUCCESSFULLY_REGISTERED = 'MYTHSDESCRIPTION_SUCCESSFULLY_REGISTERED';
export const REGISTERING_MYTHSDESCRIPTION_FAILED = 'REGISTERING_MYTHSDESCRIPTION_FAILED';


export const REGISTERED_MYTHSDESCRIPTION_FETCHED_SUCCESSFULLY = 'REGISTERED_MYTHSDESCRIPTION_FETCHED_SUCCESSFULLY';
export const REGISTERED_MYTHSDESCRIPTION_EMPTY_RESULTS = 'REGISTERED_MYTHSDESCRIPTION_EMPTY_RESULTS';
export const ERROR_FETCHING_MYTHSDESCRIPTION = 'ERROR_FETCHING_MYTHSDESCRIPTION';



