export const COUNTYDEATHS_SUCCESSFULLY_REGISTERED = 'COUNTYDEATHS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_COUNTYDEATHS_FAILED = 'REGISTERING_COUNTYDEATHS_FAILED';


export const REGISTERED_COUNTYDEATHS_FETCHED_SUCCESSFULLY = 'REGISTERED_COUNTYDEATHS_FETCHED_SUCCESSFULLY';
export const REGISTERED_COUNTYDEATHS_EMPTY_RESULTS = 'REGISTERED_COUNTYDEATHS_EMPTY_RESULTS';
export const ERROR_FETCHING_COUNTYDEATHS = 'ERROR_FETCHING_COUNTYDEATHS';

export const COUNTY_DEATH_INCREASED_SUCCESSFULLY = 'COUNTY_DEATH_INCREASED_SUCCESSFULLY';
export const ERROR_INCREASING_COUNTY_DEATH = 'ERROR_INCREASING_COUNTY_DEATH'

