export const TESTING_SUCCESSFULLY_REGISTERED = 'TESTING_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TESTING_FAILED = 'REGISTERING_TESTING_FAILED';


export const REGISTERED_TESTING_FETCHED_SUCCESSFULLY = 'REGISTERED_TESTING_FETCHED_SUCCESSFULLY';
export const REGISTERED_TESTING_EMPTY_RESULTS = 'REGISTERED_TESTING_EMPTY_RESULTS';
export const ERROR_FETCHING_TESTING = 'ERROR_FETCHING_TESTING';



