export const MYTHS_SUCCESSFULLY_REGISTERED = 'MYTHS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_MYTHS_FAILED = 'REGISTERING_MYTHS_FAILED';


export const REGISTERED_MYTHS_FETCHED_SUCCESSFULLY = 'REGISTERED_MYTHS_FETCHED_SUCCESSFULLY';
export const REGISTERED_MYTHS_EMPTY_RESULTS = 'REGISTERED_MYTHS_EMPTY_RESULTS';
export const ERROR_FETCHING_MYTHS = 'ERROR_FETCHING_MYTHS';



