export const SYMPTOMS_SUCCESSFULLY_REGISTERED = 'SYMPTOMS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_SYMPTOMS_FAILED = 'REGISTERING_SYMPTOMS_FAILED';


export const REGISTERED_SYMPTOMS_FETCHED_SUCCESSFULLY = 'REGISTERED_SYMPTOMS_FETCHED_SUCCESSFULLY';
export const REGISTERED_SYMPTOMS_EMPTY_RESULTS = 'REGISTERED_SYMPTOMS_EMPTY_RESULTS';
export const ERROR_FETCHING_SYMPTOMS = 'ERROR_FETCHING_SYMPTOMS';



