export const STRESSCOPING_SUCCESSFULLY_REGISTERED = 'STRESSCOPING_SUCCESSFULLY_REGISTERED';
export const REGISTERING_STRESSCOPING_FAILED = 'REGISTERING_STRESSCOPING_FAILED';


export const REGISTERED_STRESSCOPING_FETCHED_SUCCESSFULLY = 'REGISTERED_STRESSCOPING_FETCHED_SUCCESSFULLY';
export const REGISTERED_STRESSCOPING_EMPTY_RESULTS = 'REGISTERED_STRESSCOPING_EMPTY_RESULTS';
export const ERROR_FETCHING_STRESSCOPING = 'ERROR_FETCHING_STRESSCOPING';



