export const SCAMDESCRIPTION_SUCCESSFULLY_REGISTERED = 'SCAMDESCRIPTION_SUCCESSFULLY_REGISTERED';
export const REGISTERING_SCAMDESCRIPTION_FAILED = 'REGISTERING_SCAMDESCRIPTION_FAILED';


export const REGISTERED_SCAMDESCRIPTION_FETCHED_SUCCESSFULLY = 'REGISTERED_SCAMDESCRIPTION_FETCHED_SUCCESSFULLY';
export const REGISTERED_SCAMDESCRIPTION_EMPTY_RESULTS = 'REGISTERED_SCAMDESCRIPTION_EMPTY_RESULTS';
export const ERROR_FETCHING_SCAMDESCRIPTION = 'ERROR_FETCHING_SCAMDESCRIPTION';



