export const TRAVEL_SUCCESSFULLY_REGISTERED = 'TRAVEL_SUCCESSFULLY_REGISTERED';
export const REGISTERING_TRAVEL_FAILED = 'REGISTERING_TRAVEL_FAILED';


export const REGISTERED_TRAVEL_FETCHED_SUCCESSFULLY = 'REGISTERED_TRAVEL_FETCHED_SUCCESSFULLY';
export const REGISTERED_TRAVEL_EMPTY_RESULTS = 'REGISTERED_TRAVEL_EMPTY_RESULTS';
export const ERROR_FETCHING_TRAVEL = 'ERROR_FETCHING_TRAVEL';



