export const MEASURES_SUCCESSFULLY_REGISTERED = 'MEASURES_SUCCESSFULLY_REGISTERED';
export const REGISTERING_MEASURES_FAILED = 'REGISTERING_MEASURES_FAILED';


export const REGISTERED_MEASURES_FETCHED_SUCCESSFULLY = 'REGISTERED_MEASURES_FETCHED_SUCCESSFULLY';
export const REGISTERED_MEASURES_EMPTY_RESULTS = 'REGISTERED_MEASURES_EMPTY_RESULTS';
export const ERROR_FETCHING_MEASURES = 'ERROR_FETCHING_MEASURES';



