export const QUESTIONS_SUCCESSFULLY_REGISTERED = 'QUESTIONS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_QUESTIONS_FAILED = 'REGISTERING_QUESTIONS_FAILED';


export const REGISTERED_QUESTIONS_FETCHED_SUCCESSFULLY = 'REGISTERED_QUESTIONS_FETCHED_SUCCESSFULLY';
export const REGISTERED_QUESTIONS_EMPTY_RESULTS = 'REGISTERED_QUESTIONS_EMPTY_RESULTS';
export const ERROR_FETCHING_QUESTIONS = 'ERROR_FETCHING_QUESTIONS';



