export const SYSTEM_ADMIN = "SYSTEM_ADMIN";
export const COMPANY_OWNER = "COMPANY_OWNER";
export const REGULAR_SYSTEM_USER = "REGULAR_SYSTEM_USER";
export const IDLE_TIMEOUT = 1000 * 60;
export const DEBOUNCE = 250;

export const DISPLAY_CHILDREN_TIPS_PAGE = "DISPLAY_CHILDREN_TIPS_PAGE";
export const DISPLAY_CHILDREN_TIPS_DESCRIPTIONS_PAGE = "DISPLAY_CHILDREN_TIPS_DESCRIPTIONS_PAGE";
export const DISPLAY_MEASURE_PAGE = "DISPLAY_MEASURE_PAGE";
export const DISPLAY_MEASUREDESCRIPTION_PAGE = "DISPLAY_MEASUREDESCRIPTION_PAGE";
export const DISPLAY_MYTHS_PAGE = "DISPLAY_MYTHS_PAGE";
export const DISPLAY_MYTHSDESCRIPTION_PAGE = "DISPLAY_MYTHSDESCRIPTION_PAGE";
export const DISPLAY_PREVENTION_PAGE = "DISPLAY_PREVENTION_PAGE";
export const DISPLAY_PREVENTIONDESCRIPTION_PAGE = "DISPLAY_PREVENTIONDESCRIPTION_PAGE";
export const DISPLAY_QUESTION_PAGE = "DISPLAY_QUESTION_PAGE";
export const DISPLAY_QUESTIONDESCRIPTION_PAGE = "DISPLAY_QUESTIONDESCRIPTION_PAGE";
export const DISPLAY_SCAM_PAGE = "DISPLAY_SCAM_PAGE";
export const DISPLAY_SCAMDESCRIPTION_PAGE = "DISPLAY_SCAMDESCRIPTION_PAGE";
export const DISPLAY_STRESSCOPING_PAGE = "DISPLAY_STRESSCOPING_PAGE";
export const DISPLAY_STRESSCOPINGDESCRIPTION_PAGE = "DISPLAY_STRESSCOPINGDESCRIPTION_PAGE";
export const DISPLAY_SYMPTOM_PAGE = "DISPLAY_SYMPTOM_PAGE";
export const DISPLAY_SYMPTOMDESCRIPTION_PAGE = "DISPLAY_SYMPTOMDESCRIPTION_PAGE";
export const DISPLAY_TESTING_PAGE = "DISPLAY_TESTING_PAGE";
export const DISPLAY_TESTINGDESCRIPTION_PAGE = "DISPLAY_TESTINGDESCRIPTION_PAGE";
export const DISPLAY_TRAVEL_PAGE = "DISPLAY_TRAVEL_PAGE";
export const DISPLAY_TRAVELDESCRIPTION_PAGE = "DISPLAY_TRAVELDESCRIPTION_PAGE";
export const DISPLAY_TREATMENT_PAGE = "DISPLAY_TREATMENT_PAGE";
export const DISPLAY_TREATMENTDESCRIPTION_PAGE = "DISPLAY_TREATMENTDESCRIPTION_PAGE";


